name: Lint & Unit/Instrumentation Tests

on:
  push:
    branches:
      - development
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  gradle-lint-test:
    name: Gradle Lint And Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run Gradle lint
        run: ./gradlew lintDebug
      - name: Run Gradle test
        run: ./gradlew test
      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: subvt-data/build/reports/tests/testDebugUnitTest/
  instrumentation-test:
    name: Instrumentation Test
    needs: [gradle-lint-test]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 24
          script: ./gradlew connectedCheck
      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: instrumentation_test_report
          path: subvt-data/build/reports/androidTests/connected/